---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - config-manager.yuno.org
  resources:
  - nodegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config-manager.yuno.org
  resources:
  - nodegroups/finalizers
  verbs:
  - update
- apiGroups:
  - config-manager.yuno.org
  resources:
  - nodegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config-manager.yuno.org
  resources:
  - nodeinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config-manager.yuno.org
  resources:
  - nodeinstances/finalizers
  verbs:
  - update
- apiGroups:
  - config-manager.yuno.org
  resources:
  - nodeinstances/status
  verbs:
  - get
  - patch
  - update
